# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TofuDrift < Formula
  desc "Find drift, unmanaged and idle AWS resources in an OpenTofu/Terraform state"
  homepage "https://github.com/wardbox/tofu-drift"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/wardbox/tofu-drift/releases/download/v0.1.0/tofu-drift_0.1.0_darwin_amd64.tar.gz"
      sha256 "1546b5a17ef9b43a9d0fc8ff5524179ef1236dab1679247fc84f651f0b6210d5"

      define_method(:install) do
        bin.install "tofu-drift"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/wardbox/tofu-drift/releases/download/v0.1.0/tofu-drift_0.1.0_darwin_arm64.tar.gz"
      sha256 "3b8f05211eec8990c374ed15da0ced53a03bf1bac14ff982886e8e816f30233c"

      define_method(:install) do
        bin.install "tofu-drift"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/wardbox/tofu-drift/releases/download/v0.1.0/tofu-drift_0.1.0_linux_amd64.tar.gz"
      sha256 "ea645599a4b86d34e8216116eda53c373b3958b14973111e9925f9bdf76bf261"
      define_method(:install) do
        bin.install "tofu-drift"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/wardbox/tofu-drift/releases/download/v0.1.0/tofu-drift_0.1.0_linux_arm64.tar.gz"
      sha256 "289f6625250883f35c7edd86942c815347efea5c71f68baa84369eecfd0a6d61"
      define_method(:install) do
        bin.install "tofu-drift"
      end
    end
  end

  test do
    system "#{bin}/tofu-drift", "--version"
  end
end
